djangop/djangop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dev/', include('main.urls.dev')),
    url(r'^forum/', include('main.urls.forum')),
    url(r'^sandbox/', include('main.urls.sandbox', )),
    url(r'^api/', include('main.urls.api')),
    url(r'^', include('main.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangop/main/models.py
"""
Last edited by James Scarrow 2020-03-20
"""
import uuid
from datetime import datetime
# from djmoney.models.fields import MoneyField
from decimal import Decimal

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models, transaction
# ugetext_lazy is used for translating text to local language
# This should eventually be done manually
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from main.exceptions import *
from .managers import UserManager


# Database is in a prototype version right now and is mostly just being used to test outside functions such as player
# login, death etc. Should be reevaluated once all outside functions are working. Should consider keeping other games
# in mind when creating database do reduce future effort when more games are added.


# This is a model for the games. I'm not sure if it's more efficiant to keep a list of the usernames here or have
# The users be in game
# This model may be outdated, Should instead use serverplayer

class User(AbstractBaseUser, PermissionsMixin):
    """
    Represents a user. Contains their information and their balance. Their email is considered their username.
    """
    email = models.EmailField(_('Email Address'), unique=True, blank=False, null=False)
    user_name = models.CharField(_('Username'), max_length=30, blank=False, null=False, unique=True)

    date_joined = models.DateTimeField(_('Date Joined'), auto_now_add=True, blank=False, null=False)
    is_staff = models.BooleanField(_('Staff'), default=False)
    is_active = models.BooleanField(_('Active'), default=True)

    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        if not self.pk:
            if not self.email or not self.user_name or not self.password:
                raise TypeError
        super(User, self).save(*args, **kwargs)

    def get_full_name(self):
        # The user is identified by their email address
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    if __name__ == '__main__':
        class Meta:
            verbose_name = _('User')
            verbose_name_plural = _('Users')


class Developer(models.Model):
    company_name = models.CharField(_('First Name'), max_length=30, blank=False, null=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        if self.user is None or not self.company_name.strip():
            raise TypeError
        super(Developer, self).save(*args, **kwargs)


class Game(models.Model):
    """
    Represents the game. Should be created when the developer registers a new game. The key should be kept secret
    because it is used to start and access matches that belong to the game. Name is the name of the game. date_joined
    is the date the Game was created.
    """

    # The name of the game
    name = models.CharField(max_length=100, blank=False, null=False)
    key = models.CharField(max_length=100, blank=False, unique=True, default=uuid.uuid4)

    date_created = models.DateTimeField(_('Date Created'), auto_now_add=True)

    developer = models.ForeignKey(Developer, blank=False, unique=False, on_delete=models.CASCADE)

    approved = models.BooleanField(_('Approved'), blank=False, default=False)

    max_match_length = models.IntegerField(blank=False, null=False, default=1)

    # Game they don't need to create user groups every time they create a match.

    def save(self, *args, **kwargs):
        if not self.name or not self.name.strip():
            raise GameCreateError('Name cannot be empty.')

        if not self.pk:
            if self.date_created is not None:
                raise GameCreateError('Cannot set date created. This is done automatically.')
            if self.developer.game_set.filter(name=self.name).count() != 0:
                raise GameCreateError('User cannot create more than one game with the same name')
        super(Game, self).save(*args, **kwargs)

    def set_all_sandbox_players_balance(self, amount):
        for sandbox_player in self.sandboxplayer_set.all():
            sandbox_player.balance = amount
            sandbox_player.save()

    def delete_all_sandbox_players(self):
        self.sandboxplayer_set.all().delete()

    def update_sandbox_player(self, player_id, name, balance, password):
        sandbox_player = self.sandboxplayer_set.get(id=player_id)
        sandbox_player.name = name
        sandbox_player.balance = balance
        sandbox_player.password = password
        sandbox_player.save()

    def delete_sandbox_player(self, player_id):
        self.sandboxplayer_set.filter(id=player_id).delete()

    def create_sandbox_player(self, name, balance):
        self.sandboxplayer_set.create(name=name, balance=balance)

    def create_sandbox_players(self, prefix, count, balance):
        with transaction.atomic():
            starting_index = self.sandboxplayer_set.count()
            SandboxPlayer.objects.bulk_create([SandboxPlayer(name=prefix + str(x), game=self, balance=balance) for
                                               x in range(starting_index, starting_index+count)])

    def delete_all_sandbox_matches(self):
        self.sandboxplayer_set.all().delete()

    def create_sandbox_match_type(self, name):
        self.sandboxmatchtype_set.create(name=name)

    def delete_sandbox_match_type(self, match_type_id):
        self.sandboxmatchtype_set.filter(id=match_type_id).delete()

    def update_name(self, name):
        with transaction.atomic():
            self.name = name
            self.save()


class Match(models.Model):
    """
    A match in the game. Contains the amount of money currently in the pool. A unique key to access the match.
    Each match belongs to a game. Has a date created and date finished fields. The date_finished field should be
    set when the match is over. The date_finished is set to the same value as date_created when the Match is created,
    this is how you can tell the match is still going.
    """
    # The amount of money in the pool
    pool = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # The wager amount for the match
    wager = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # A unique identifier to be used to access the game
    key = models.CharField(max_length=100, blank=False, unique=False, default=uuid.uuid4)

    # The game the match belongs to
    game = models.ForeignKey(Game, blank=True, unique=False, on_delete=models.CASCADE)

    # Date the game started
    date_created = models.DateTimeField(_('Date Joined'), auto_now_add=True)
    # Date the game finished. Set to same as start date, should be set when the game is over
    date_finished = models.DateTimeField(_('Date Finished'), auto_now_add=True)


class PlayerGroup(models.Model):
    """
    Represents a UserGroup within a match. Contains a set of users. This can be used for assigning users
    to teams in a match. A UserGroup belongs to a match.
    """
    # The Match the UserGroup belongs to
    match = models.ForeignKey(Match, blank=False, on_delete=models.CASCADE)
    # Name of the UserGroup
    name = models.CharField(max_length=100, blank=True)


class Player(models.Model):

    # First and last name should be required in the future
    first_name = models.CharField(_('First Name'), max_length=30, blank=False)
    last_name = models.CharField(_('Last Name'), max_length=30, blank=False)

    in_game = models.BooleanField(_('In Game'), default=False)
    wager = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)


class PlayerGroupPlayer(models.Model):
    player = models.ForeignKey(Player, blank=False, on_delete=models.CASCADE)
    player_group = models.ForeignKey(PlayerGroup, blank=False, on_delete=models.CASCADE)

# ---------------------------------------------------- Sandbox ---------------------------------------------------------


class SandboxMatchType(models.Model):
    """
    Represents a type of match a sandbox game can have, e.g. Team Deathmatch, Free for all. It is not necessary for
    a match to have a match type but it can be useful for automatically setting up the match to have certain properties,
    such as groups that are created with the match (implementing) or preset payout schemes (idea).
    """
    name = models.CharField(max_length=50, blank=False, null=False)
    game = models.ForeignKey(Game, blank=False, null=False, on_delete=models.CASCADE)
    max_match_length = models.IntegerField(blank=False, null=False, default=60)

    def save(self, *args, **kwargs):

        if not self.name or not self.name.strip():
            raise MatchTypeCreationError("Error: Cannot create a match type without a name")
        if (not self.pk and self.game.sandboxmatchtype_set.filter(name=self.name).count() > 0) or  \
                (self.pk is not None and (self.name != SandboxMatchType.objects.get(id=self.pk).name)):
            raise MatchTypeCreationError("Error: Game already has a match type with the given name.")
        super(SandboxMatchType, self).save(*args, **kwargs)


class SandboxMatchTypeGroup(models.Model):
    """
    A preset group for a SandboxMatchType. When a match with a given match type is created player groups will
    automatically be created for each match type group belonging to the match type.
    """
    name = models.CharField(max_length=50, blank=False)
    match_type = models.ForeignKey(SandboxMatchType, blank=False, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):

djangop/main/forms.py
from django import forms

from .models import User

class UserLoginForm(forms.ModelForm):

    class Meta:
        password = forms.CharField(widget=forms.PasswordInput)
        model = User
        widgets = {
            'password' : forms.PasswordInput(),
        }
        fields = ('email', 'password')

djangop/main/views/forum.py
from django.shortcuts import render, redirect

from main.models import Category, Thread, Message


def index(request):
    return render(request, 'main/forum/index.html')


def category(request, category):

    if request.method == "POST":
        title = request.POST["title"]
        text = request.POST["message"]
        c = Category.objects.get(name=category)
        thread = Thread(title=title,category=c)
        thread.save()
        m = Message(text=text, user=request.user, thread=thread)
        m.save()
        return redirect("/forum/" + category + "/" + str(thread.id))


    # For now we're just going to have a developer forum
    threads = Category.objects.get(name=category).thread_set.all()

    return render(request, 'main/forum/category.html', {'category' : category, 'threads' : threads})


def thread(request, category, thread):

    if request.method == "POST":
        text = request.POST['message']
        post = Message(text=text, thread=Thread.objects.get(category__name=category,id=thread), user=request.user)
        post.save()

    t = Thread.objects.get(category__name=category, id=thread)
    t.views += 1
    t.save()
    messages = t.message_set.all()

    return render(request, 'main/forum/thread.html', {'thread' : t.title, 'category' : category, 'messages' : messages})

def newthread(request):
    return render(request, 'main/forum/newthread.html')

djangop/main/templates/main/dev/sandbox/home.html
<div class="container-fluid">
<h1>{{ game.name }} <small style="color: #0f0f0f">Key: {{ game.key }}</small></h1>
    <div>
        <hr style="width: 100%; color: black; height: 1px; background-color:black;" />
        <div class="col-md-6">
            <h2>Total Matches: {{ game.sandboxmatch_set.count }}</h2>
            <div class="col-md-12">
                <h3>Registering Matches: {{ registering_matches_count }}</h3>
                <h3>Active Matches: {{ active_matches_count }}</h3>
                <h3>Finished Matches: {{ finished_matches_count }}</h3>
                <h3>Aborted Matches: {{ aborted_matches_count }}</h3>
            </div>

        </div>
        <div class="col-md-6">
            <h2>Match Types: {{ game.sandboxmatchtype_set.count }}</h2>
            <h2>Max Match Length: {{ game.max_match_length }} min</h2>
            <h2>Players: {{ game.sandboxplayer_set.count }}</h2>
        </div>
    </div>
</div>

djangop/main/templates/main/dev/sandbox/match.html
{# TODO: This page should display the match type #}
<script>
    $(".matchLink").click(function () {

        $.ajax({
              dataType: "text",
              url: "match/" + {{ match.id }} + "/",
              // When the data is received from the request, do this:
              success: function (result) {
                  $("#content").html(result.toString());
              }
          })
    })
</script>

<h1>Match <small><a class="matchLink" style="cursor: pointer">{{  match.key }}</a></small></h1>

<div class="row content">
    <div class="col-md-4">
        <h3>Created: {{ match.date_started }}</h3>
        <h3>Wager: {{ match.wager }}</h3>
        <h3>Pool: {{ match.maxPool }}</h3>
    </div>

    <div class="col-md-6">

        {% if match.state == 0 %}
            <h3>
                Registering
            </h3>
        {% elif match.state == 1 %}
            <h3>
                Started {{ match.date_started }}
            </h3>
        {% elif match.state == 2 %}
            <h3>
                Started {{ match.date_started }}
            </h3>
            <h3>
                Finished {{ match.date_finished }}
            </h3>
            <h3>
                Winning Group: {{ match.winning_player_group.get_name }}
            </h3>
        {% else %}
            <h3>
            {% if match.date_started is None %}
                Match didn't start
            {% else %}
                Started {{ match.date_started }}
            {% endif %}
            </h3>
            <h3>
                Aborted {{ match.date_finished }}
            </h3>
        {% endif %}
    </div>
</div>
<br>
<h2>Groups:</h2>
<hr>
<div class="col-md-12">

    {% for group in match.sandboxplayergroup_set.all %}
        {% if not group.removed %}
            <h3>{{ group.get_name }}<small> {{ group.getPlayers|length }} player(s)</small>
        {% else %}
            <h3 style="color: red;">{{ group.get_name }}<small style="color: red"> *removed*</small>
        {% endif %}
        </h3>
        <hr>
        {% for player in group.sandboxplayergroupplayer_set.all %}
            {% if not player.quit %}
                <h4>{{ player.player.name }}</h4>
            {% else %}
                <h4 style="color: red">{{ player.player.name }} *quit*</h4>
            {% endif %}
        {% endfor %}
    {% endfor %}
</div>

djangop/main/templates/main/dev/sandbox/matchType.html
{% load static %}

<script type="application/javascript" src="{% static 'main/js/dev.js'%}"></script>
<script>
    $(function () {
        maxMatchLength({{ matchType.id }}, {{ matchType.max_match_length }});
    });

    var addGroupPresetBtn = $("#addGroupPresetButton");

    addGroupPresetBtn.click( function () {
            var name = $("#addGroupPresetInput").val();
            $.post('settings/', {
                operation: 'addGroupPreset',
                name: name,
                matchType: {{ matchType.id }},
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val()
            }).done(
                function (result) {
                    window.location.reload()
                }
            )
        });

    function deleteGroupPreset(id) {
            $.post('settings/', {
                operation: 'deleteGroupPreset',
                id: id,
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val()
            }).done(
                function (result) {
                    window.location.reload()
                }
            )
        }
</script>

<h1>Match Type <small><a class="matchLink" style="cursor: pointer">{{ matchType.name }}</a></small></h1>
<div id="maxMatchLength">
    {% include 'main/dev/sandbox/matchType/maxMatchLength.html' %}
</div>

{% csrf_token %}
{% if matchType.sandboxmatchtypegroup_set.count == 0 %}
    <br>
    <h3 style="color: red">You haven't added any groups for this match type yet.</h3>
    <br>
    <br>
{% else %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Group Presets</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for group in matchType.sandboxmatchtypegroup_set.all %}
            <tr>
                <td>{{ group.name }}</td>
                <td><button class="btn btn-danger" onclick="deleteGroupPreset({{ group.id }})">Delete</button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

<div class="row">
    <div class="col-md-3 col-sm-12" style="padding-bottom: 5px">
        <input class="form-control" type="test" id="addGroupPresetInput" placeholder="Name"/>
    </div>
    <div class="col-md-2 col-sm-12">
        <button class="btn btn-success" id="addGroupPresetButton">Add Group Preset</button>
    </div>
</div>

djangop/main/templates/main/dev/sandbox/matchTypes.html
<script>

    var addMatchTypeBtn = $("#addMatchTypeButton");

    addMatchTypeBtn.click( function () {
            var name = $("#addMatchTypeInput").val();
            $.post('settings/', {
                operation: 'addMatchType',
                name: name,
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val()
            }).done(
                function (result) {
                    window.location.reload()
                }
            )
        });

    function deleteMatchType(id) {
            $.post('settings/', {
                operation: 'deleteMatchType',
                id: id,
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val()
            }).done(
                function (result) {
                    window.location.reload()
                }
            )
        }

    $(".matchTypeLink").click(function () {
        var matchTypeId = this.id;
        $.ajax({
              dataType: "text",
              url: "matchtype/" + this.id + "/",
              // When the data is received from the request, do this:
              success: function (result) {
                  $("#content").html(result.toString());
                  var location = "dev/sandbox/{{ game.id }}/matchtype/" + matchTypeId + "/";
                  sessionStorage.setItem("sandboxControlPanelTab" + {{ game.id }}, location)
              }
          })
    });
</script>

{% csrf_token %}

{% if matchTypes.count == 0 %}
    <br>
    <h3 style="color: red">You haven't added any match types for this game yet.</h3>
    <br>
    <br>
{% else %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Match Types</th>
        </tr>
        </thead>
        <tbody>
        {% for matchType in matchTypes %}
            <tr>
                <td><a id="{{ matchType.id }}" class="matchTypeLink" style="cursor: pointer">{{ matchType.name }}</a></td>
                <td><button class="btn btn-danger" onclick="deleteMatchType({{matchType.id}})">Delete</button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

<div class="row">
    <div class="col-md-3 col-xs-12" style="padding-bottom: 5px">
        <input class="form-control" type="test" id="addMatchTypeInput" placeholder="Name" />
    </div>
    <div class="co-md-2 col-xs-12">
        <button class="btn btn-success" id="addMatchTypeButton">Add Match Type</button>
    </div>
</div>

djangop/main/templates/main/dev/sandbox/matches.html
<script>
    $(".matchLink").click(function () {
        var id = this.id;
        $.ajax({
              dataType: "text",
              url: "match/" + this.id + "/",
              // When the data is received from the request, do this:
              success: function (result) {
                  $("#content").html(result.toString());
                  console.log({{ game.id }});
                  var location = "dev/sandbox/{{ game.id }}/match/" + id + "/";
                  sessionStorage.setItem("sandboxControlPanelTab" + {{ game.id }}, location)
              }
          })
    })
</script>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Key</th>
        <th>Type</th>
        <th>Created</th>
        <th>Created</th>
        <th>Pool</th>
        <th>Wager</th>
    </tr>
    </thead>
    <tbody>
    {% for match in matches.all reversed %}
        <tr>
            <td><a id="{{ match.id }}" class="matchLink" style="cursor: pointer">{{ match.key }}</a></td>
            <td>{{ match.type.name }}</td>
            <td>{{ match.date_created }}</td>
            <td>
                {% if match.state == 0 %}
                    Registering
                {% elif match.state == 1 %}
                    Started {{ match.date_started }}
                {% elif match.state == 2 %}
                    Finished {{ match.date_finished }}
                {% else %}
                    Aborted {{ match.date_finished }}
                {% endif %}

            </td>
            <td>{{ match.pool }}</td>
            <td>{{ match.wager }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

djangop/main/templates/main/dev/sandbox/players.html
<script>
        // When the new player button is clicked
        $("#addPlayer").click( function () {
            $.post("players/", { name: $("#name").val(),
                balance: $("#balance").val(),
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val() }).done(
                function (result) {
                    $("#content").html(result.toString());
                }
            )
        });

        function decimalInput(input) {
            var v = parseFloat(input.value);
            if (isNaN(v)) {
                input.value = '';
            } else {
                input.value = v.toFixed(2);
            }
        }

        // Only allow two decimal places in the balance textbox
        $("#balance").change(function () {
            decimalInput(this);
        });

        $("#allBalances").change(function () {
            decimalInput(this);
        });

        // When the edit button is clicked
        function editButtonClicked(button) {
            if ($("#changename").length) {
                $("#errorMessage").text("Only one player can be changed at a time.");
                return;
            }
            {# Change the name field to a textbox #}
            $("#name"+button.id).html('<input id="changename" class="form-control" value="'
                +$("#name"+button.id).html()+'">');
            {# Change the password field to a textbox #}
            $("#password"+button.id).html('<input id="changepassword" class="form-control" value="'
                +$("#password"+button.id).html()+'">');
            {# Change the balance field to a textbox #}
            $("#balance"+button.id).html('<input id="changebalance" class="form-control" value="'
                +$("#balance"+button.id).html()+'">');
            $("#changebalance").change( function() {
                decimalInput(this);
            });

            {# Add a delete button #}
            $("#buttons"+button.id).append('  <button class="btn btn-info editButton" id="delete'+button.id+'" style="background-color: #ff1513; border-color: #ff1513">Delete</button>');
            $('#delete'+button.id).click( function() {
                $.post("players/", {
                    id: button.id,
                    delete: 'yes',
                    csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val() }).done(
                        function(result) {
                            $("#content").html(result.toString());
                        })
            });

            {# Change this buttons text #}
            $(button).text("Save");
            {# When the save button is clicked #}
            $(button).off('click').click( function() {
                $.post("players/", {
                    id: button.id,
                    name: $("#changename").val(),
                    balance: $("#changebalance").val(),
                    password: $("#changepassword").val(),
                    csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val() }).done(
                        function(result) {
                            $("#content").html(result.toString());
                        })
            })
        }


        $(".editButton").click(function() {
            editButtonClicked(this);
        });

        $("#resetBalances").click(function () {
            $.post("players/", {
                all: 'yes',
                amount: $("#allBalances").val(),
                csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val()}).done(
                    function (result) {
                        $("#content").html(result.toString());
                    })
        });


        // When the edit button is clicked for a

</script>
{% if players.count == 0 %}
    <br>
    <h3 style="color: red">You haven't added any sandbox players for this game yet. Add some players to start testing your game!</h3>
    <br>
    <br>
{% else %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Password</th>
            <th>Balance</th>
            <th>Date created</th>
        </tr>
        </thead>
        <tbody>
        {% for player in players.all %}
            <tr>
                <td id="name{{ player.id }}">{{ player.name }}</td>
                <td id="password{{ player.id }}">{{ player.password }}</td>
                <td id="balance{{ player.id }}">{{ player.balance }}</td>
                <td>{{ player.date_created }}</td>
                <td id="buttons{{ player.id }}"><button class="btn btn-info editButton" id="{{ player.id }}">Edit</button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
<p style="color: red" id="errorMessage"></p>
<div class="row">
        {% csrf_token %}
        <div class="col-md-2">
            <input class="btn btn-info" value="Add Player" id="addPlayer" type="submit">
        </div>
        <div class="col-md-4 col-xs-12 span6" style="padding-bottom: 5px">
            <label for="name">Name: </label>
            <input name="name" id="name" class="form-control">
        </div>
        <div class="col-md-4 col-xs-12 span6">
            <label for="balance">Balance: $</label>
            <input name="balance" id="balance" class="form-control">
        </div>
</div>
<br>
{% if players.count != 0 %}
<div class="row">
    <div class="col-md-2">
            <input class="btn btn-info" value="Set All Balances" id="resetBalances" type="submit" style="background-color: #ff1513; border-color: #ff1513">
        </div>
        <div class="col-md-4 span6" >
            <label for="allBalances">Amount: $</label>
            <input name="name" id="allBalances" class="form-control">
        </div>
        <div class="col-md-4 span6">
        </div>
</div>
{% endif %}